### ISSUE TITLE
Support for version 200?

### ISSUE THREAD

**Issue by Benjythebee** [sh-dave/haxe-format-vox#1]
The latest MagicaVoxel 0.99.7.0 .vox format has apparently version=200 (rather than 150);

This causes the voxel reader to fail.

Would it be possible to have an update so version 200 .vox files are readable? This tool has been useful and reliable for years, it would be sad to see it die down due to a new .vox version.

It is also possible that not much has changed from version 150 to 200;

**Comment by Benjythebee** [comment]
made a fork that just adds `&& !version ==200` 
https://github.com/sh-dave/haxe-format-vox.git

Seem to work just fine

**Comment by sh-dave** [comment]
Open a PR and I'll merge it.

**Comment by Benjythebee** [comment]
Fixed

https://github.com/sh-dave/haxe-format-vox/pull/2

**Comment by Benjythebee** [comment]
hey @sh-dave ; could we have a release on npm ?

**Comment by sh-dave** [comment]
Sure, done.
